# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/semenov/Desktop/speaker_project/ultrasonicSpeaker/ultrasonicSpeaker.srcs/sources_1/ip/combined_clock_gen/combined_clock_gen.xci
# IP: The module: 'combined_clock_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/semenov/Desktop/speaker_project/ultrasonicSpeaker/ultrasonicSpeaker.gen/sources_1/ip/combined_clock_gen/combined_clock_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'combined_clock_gen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/semenov/Desktop/speaker_project/ultrasonicSpeaker/ultrasonicSpeaker.gen/sources_1/ip/combined_clock_gen/combined_clock_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'combined_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/semenov/Desktop/speaker_project/ultrasonicSpeaker/ultrasonicSpeaker.gen/sources_1/ip/combined_clock_gen/combined_clock_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'combined_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/semenov/Desktop/speaker_project/ultrasonicSpeaker/ultrasonicSpeaker.srcs/sources_1/ip/combined_clock_gen/combined_clock_gen.xci
# IP: The module: 'combined_clock_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/semenov/Desktop/speaker_project/ultrasonicSpeaker/ultrasonicSpeaker.gen/sources_1/ip/combined_clock_gen/combined_clock_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'combined_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/semenov/Desktop/speaker_project/ultrasonicSpeaker/ultrasonicSpeaker.gen/sources_1/ip/combined_clock_gen/combined_clock_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'combined_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/semenov/Desktop/speaker_project/ultrasonicSpeaker/ultrasonicSpeaker.gen/sources_1/ip/combined_clock_gen/combined_clock_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'combined_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
